export const ALGORITHM_CONFIG = {
    HIGH_ERROR_THRESHOLD: 0.4,
    LOW_ERROR_THRESHOLD: 0.15,
    HIGH_ERROR_MULTIPLIER: 2.0,
    LOW_ERROR_MULTIPLIER: 0.5,
    MAX_WEIGHT: 10,
    MIN_WEIGHT: 0.5,
    DEFAULT_WEIGHT: 1.0
} as const;
