import { useQuery } from '@tanstack/react-query';
import { z } from 'zod';

const ModeCountsSchema = z.object({
    quiz: z.number().int().nonnegative(),
    bugFinding: z.number().int().nonnegative(),
    codeCompletion: z.number().int().nonnegative()
});

/**
 * Shape of `public/data/manifest.json` — generated by `npm run build:manifest`.
 * `matrix` holds the exact count per difficulty x mode pair; the per-axis
 * `counts` cannot be combined into one, because the axes are not independent.
 *
 * Validated at runtime: the SPA rewrite answers a missing file with index.html
 * (HTTP 200), and a manifest from an older deploy has no `matrix` — both must
 * surface as an error the user can retry, not as an empty category list.
 */
const ManifestEntrySchema = z.object({
    slug: z.string(),
    displayName: z.string(),
    counts: z.object({
        easy: z.number().int().nonnegative(),
        medium: z.number().int().nonnegative(),
        hard: z.number().int().nonnegative(),
        total: z.number().int().nonnegative(),
        quiz: z.number().int().nonnegative(),
        bugFinding: z.number().int().nonnegative(),
        codeCompletion: z.number().int().nonnegative()
    }),
    matrix: z.object({
        easy: ModeCountsSchema,
        medium: ModeCountsSchema,
        hard: ModeCountsSchema
    })
});

export const ManifestSchema = z.array(ManifestEntrySchema);

export type ModeCounts = z.infer<typeof ModeCountsSchema>;
export type ManifestEntry = z.infer<typeof ManifestEntrySchema>;

const MANIFEST_URL = '/data/manifest.json';

export function useCategories() {
    return useQuery({
        queryKey: ['categories', 'manifest'],
        queryFn: async () => {
            const res = await fetch(MANIFEST_URL);
            if (!res.ok) throw new Error('Failed to load categories');
            return ManifestSchema.parse(await res.json());
        },
        staleTime: Infinity
    });
}
