import { useQuery } from '@tanstack/react-query';

export interface ModeCounts {
    quiz: number;
    bugFinding: number;
    codeCompletion: number;
}

/**
 * Shape of `public/data/manifest.json` — generated by `npm run build:manifest`.
 * `matrix` holds the exact count per difficulty x mode pair; the per-axis
 * `counts` cannot be combined into one, because the axes are not independent.
 */
export interface ManifestEntry {
    slug: string;
    displayName: string;
    counts: {
        easy: number;
        medium: number;
        hard: number;
        total: number;
        quiz: number;
        bugFinding: number;
        codeCompletion: number;
    };
    matrix: {
        easy: ModeCounts;
        medium: ModeCounts;
        hard: ModeCounts;
    };
}

const MANIFEST_URL = '/data/manifest.json';

export function useCategories() {
    return useQuery({
        queryKey: ['categories', 'manifest'],
        queryFn: async () => {
            const res = await fetch(MANIFEST_URL);
            if (!res.ok) throw new Error('Failed to load categories');
            return res.json() as Promise<ManifestEntry[]>;
        },
        staleTime: Infinity
    });
}
